[2025-03-04T22:38:47.680+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: mercadolibre_tÃ©cnica.csv_to_db_task manual__2025-03-04T22:38:46.169216+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
